// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5BVb9fJyH459JAjjJ1SRda67ijiEKIkU',
    appId: '1:220417592573:web:e8a7c5d8f9b2a3c4d5e6f7',
    messagingSenderId: '220417592573',
    projectId: 'quran-a3029',
    storageBucket: 'quran-a3029.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5BVb9fJyH459JAjjJ1SRda67ijiEKIkU',
    appId: '1:220417592573:android:c42fc35777fe5b61aa4294',
    messagingSenderId: '220417592573',
    projectId: 'quran-a3029',
    storageBucket: 'quran-a3029.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5BVb9fJyH459JAjjJ1SRda67ijiEKIkU',
    appId: '1:220417592573:ios:a1b2c3d4e5f6g7h8i9j0k1',
    messagingSenderId: '220417592573',
    projectId: 'quran-a3029',
    storageBucket: 'quran-a3029.firebasestorage.app',
    iosBundleId: 'quranjourney.moustafa.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5BVb9fJyH459JAjjJ1SRda67ijiEKIkU',
    appId: '1:220417592573:ios:a1b2c3d4e5f6g7h8i9j0k1',
    messagingSenderId: '220417592573',
    projectId: 'quran-a3029',
    storageBucket: 'quran-a3029.firebasestorage.app',
    iosBundleId: 'quranjourney.moustafa.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5BVb9fJyH459JAjjJ1SRda67ijiEKIkU',
    appId: '1:220417592573:windows:a1b2c3d4e5f6g7h8',
    messagingSenderId: '220417592573',
    projectId: 'quran-a3029',
    storageBucket: 'quran-a3029.firebasestorage.app',
  );
}
